- config/routes.rb
- db/seeds.rb
> seeds almost done missing user

- app/models/character.rb
- app/views/characters/index.html.erb
- db/seeds.rb
added user to the seed => seed is done w/ user and characters
displayed characters in the  index view (with the seed)
> update seed  + index view

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_footer.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
footer ready with functional (empty) links.
> footer finished

- app/controllers/characters_controller.rb
- app/models/character.rb
- app/models/user.rb
- app/views/characters/_form.html.erb
- app/views/characters/edit.html.erb
- app/views/characters/index.html.erb
- app/views/characters/new.html.erb
- app/views/characters/show.html.erb
- db/seeds.rb
Characters controller done + form pour ajouter et editer les personnages fait !
Ajout de lien pour naviguer sur le site.
> character_controllers + form add/edit done

- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/models/booking.rb
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
- config/routes.rb
- db/migrate/20241119162620_add_default_status_to_bookings.rb
- db/schema.rb
> dashboard_d1

- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
> time_beefore

- app/assets/stylesheets/components/_form_new.scss
- app/assets/stylesheets/components/_pointeur.scss
- app/views/characters/new.html.erb
- app/views/pages/home.html.erb
> homepage modification

- app/assets/stylesheets/components/_pointeur.scss
- app/views/characters/_form.html.erb
- app/views/characters/edit.html.erb
> edit show done

- app/views/characters/show.html.erb
> view started

- app/models/booking.rb
- app/views/pages/dashboard.html.erb
- db/migrate/20241120133759_add_status_to_characters.rb
- db/migrate/20241120141537_add_booking_number_to_bookings.rb
- db/migrate/20241120141755_fill_booking_numbers.rb
- db/migrate/20241120141828_add_not_null_constraint_to_booking_number.rb
- db/migrate/20241120143129_add_booking_number_to_characters.rb
- db/schema.rb
- db/seeds.rb
nouvelle seed et dashbord mis à jour
> nouvelle seed et dashbord mis à jour

- app/assets/stylesheets/components/_form_new.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/characters/index.html.erb
- app/views/characters/show.html.erb
show view done + booking dash done css
> showview done

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/characters/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
adding add character to navbar menu, destroy only for owner on index
> adding add character to navbar menu, destroy only for owner on index

- app/views/bookings/_booking_form.html.erb
- app/views/characters/show.html.erb
- app/views/pages/dashboard.html.erb
form revu avec css / bootsrap + buttons
> view form done

- app/views/pages/dashboard.html.erb
> bug fixed booking

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
bootstrap dahsboard
mise en page 
colonne my characters en scroll
background image
> dashboard revu v1

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_title.scss
- app/controllers/pages_controller.rb
- app/views/characters/_form.html.erb
- app/views/characters/new.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/profile.html.erb
- config/routes.rb
creation de la profile page
revue de tous les forms
> forms done + profile page

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
> dashboard presque fini

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/navbar.scss
- app/views/pages/home.html.erb
revue de la navbar en sticky + positiions overflow réglée
> Validations

- app/assets/stylesheets/components/_navbar.scss
- db/seeds.rb
> seed modified + logo navbar

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/dashboard.html.erb
> btn-coulour-backroand

- app/assets/stylesheets/components/_index.scss
> delete le import pointeur

- app/assets/stylesheets/components/_footer.scss
- app/views/devise/passwords/new.html.erb
- app/views/pages/profile.html.erb
> derniers ajustements fait
